export const TYPE_ICONS: Record<string, string> = {
  normal: "/icons/1.png",
  fighting: "/icons/2.png",
  flying: "/icons/3.png",
  poison: "/icons/4.png",
  ground: "/icons/5.png",
  rock: "/icons/6.png",
  bug: "/icons/7.png",
  ghost: "/icons/8.png",
  steel: "/icons/9.png",
  fire: "/icons/10.png",
  water: "/icons/11.png",
  grass: "/icons/12.png",
  electric: "/icons/13.png",
  psychic: "/icons/14.png",
  ice: "/icons/15.png",
  dragon: "/icons/16.png",
  dark: "/icons/17.png",
  fairy: "/icons/18.png",
};
