export const TYPE_ICONS: Record<string, string> = {
  normal: "/src/icons/1.png",
  fighting: "/src/icons/2.png",
  flying: "/src/icons/3.png",
  poison: "/src/icons/4.png",
  ground: "/src/icons/5.png",
  rock: "/src/icons/6.png",
  bug: "/src/icons/7.png",
  ghost: "/src/icons/8.png",
  steel: "/src/icons/9.png",
  fire: "/src/icons/10.png",
  water: "/src/icons/11.png",
  grass: "/src/icons/12.png",
  electric: "/src/icons/13.png",
  psychic: "/src/icons/14.png",
  ice: "/src/icons/15.png",
  dragon: "/src/icons/16.png",
  dark: "/src/icons/17.png",
  fairy: "/src/icons/18.png",
};
